api/urls.py
from api.views import PostView
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()
router.register('posts', PostView)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='obtain_auth_token'),
]

instasram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('auth/', include('accounts.urls')),
    path("", include('posts.urls')),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views.base import IndexRedirectView, IndexView
from posts.views.comments import CommentDetailView, PostCommentCreateView
from posts.views.posts import PostDetail, PostCreateView


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "post/", IndexRedirectView.as_view(), name="post_index_redirect"
    ),
    path("post/add", PostCreateView.as_view(), name="post_add"),
    path("post/<int:pk>", PostDetail.as_view(), name="post_detail"),
    path("review/<int:pk>", CommentDetailView.as_view(), name="comment_detail"),
    path('post/<int:pk>/comments/add/', PostCommentCreateView.as_view(), name='post_comment_add'),
]

posts/models/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Post(models.Model):
    description = models.CharField(verbose_name='Описание', null=False, max_length=200)
    image = models.ImageField(verbose_name='Фото', null=False, blank=True, upload_to='posts')
    author = models.ForeignKey(verbose_name='Автор', to=get_user_model(), related_name='posts', null=False, blank=False,
                               on_delete=models.CASCADE, default=get_user_model())
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Время создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата и время обновления"
    )

    def __str__(self):
        return f"{self.author} - {self.description}"


class Comment(models.Model):
    author = models.ForeignKey(verbose_name='Автор', to=get_user_model(), related_name='comments', null=False,
                               blank=False,
                               on_delete=models.CASCADE)
    post = models.ForeignKey(verbose_name='Публикация', to='posts.Post', related_name='comments', null=False,
                             blank=False,
                             on_delete=models.CASCADE)
    text = models.CharField(verbose_name='Комментарий', null=False, blank=False, max_length=200)
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Время создания"
    )
    updated_at = models.DateTimeField(
        auto_now_add = True,
        verbose_name="Дата и время обновления"
    )

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    email = forms.CharField(required=True, label='Логин')
    password = forms.CharField(required=True, label='Пароль', widget=forms.PasswordInput)


class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвердите пароль', strip=False, required=True,
                                       widget=forms.PasswordInput)
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ('username', 'password', 'password_confirm', 'first_name', 'last_name', 'email', 'avatar', 'birth_date')
        labels = {'username': 'логин', 'password': 'пароль', 'password_confirm': 'подтверждение пароля', 'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email', 'avatar': 'Аватар',
                  'birth_date': 'Дата рождения'}

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        # user.groups.add('user')
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'avatar', 'birth_date')
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email', 'avatar': 'Аватар', 'birth_date': 'Дата рождения'}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']


class SearchForm(forms.Form):
    query = forms.CharField(max_length=20, required=False)

posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from posts.models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            "image",
            "description",
        )

        labels = {
            "image": "Изображение",
            "description": "Описание",
        }


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            "text",
        )

posts/views/base.py
from django.views.generic import RedirectView, ListView
from posts.models import Post


class IndexView(ListView):
    template_name = "index.html"
    model = Post
    context_object_name = "posts"
    ordering = ("-created_at",)



class IndexRedirectView(RedirectView):
    pattern_name = "index"

posts/views/comments.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import DetailView, CreateView

from posts.forms import PostCommentForm
from posts.models import Comment, Post


class CommentDetailView(DetailView):
    template_name = "comment.html"
    model = Comment


class PostCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment_create.html'
    form_class = PostCommentForm

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.post = post
        comment.author = self.request.user
        comment.save()
        return redirect('comment_detail', pk=post.pk)

posts/views/posts.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView
from posts.forms import PostForm
from posts.models import Post


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "post_create.html"
    model = Post
    form_class = PostForm
    success_message = "Пост добавлен"
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = self.request.user
            form.save()
            return redirect(self.success_url)
        context = {'form': form}
        return self.render_to_response(context)


class PostDetail(DetailView):
    template_name = "post.html"
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        comments = post.comments.all()
        context["comments"] = comments
        return context

posts/templates/partial/form.html
{% load django_bootstrap5 %}
{% csrf_token %}

{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
        {% csrf_token %}
{% endif %}
        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
        {% bootstrap_form form %}
{% if not fields_only %}
        <br/>
        <input type="submit" class="btn btn-primary" value="{{ button_text|default:"Submit" }}"/>
    </form>
{% endif %}

posts/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

posts/templates/partial/post_form.html
{% load django_bootstrap5 %}
{% csrf_token %}
{% bootstrap_form form %}

<div class="form_row">
    {% bootstrap_button button_type="submit" content=button_text %}
</div>

posts/templates/partial/post_list.html
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}


{% for post in posts %}
<div class="px-px md:px-3">
     
    <div class="flex flex-wrap -mx-px md:-mx-3">    
      <div class="w-1/3 p-px md:px-3">       
        <a href="{% url 'post_detail' post.pk %}">
            
          <article class="post bg-gray-100 relative pb-full md:mb-6">  
                   
            <img class="left-0 top-0 object-cover" src="{{ post.image.url }}" alt="image">
            
            <i class="fas fa-square absolute right-0 top-0 m-1"></i>
            <p>{{ post.description }}</p>
            
          </article>
          
        </a>
        
      </div>
      
    </div>
    
  </div>
  {% endfor %}
  




{#    <div class="box">#}
{#        <h3><a href="{% url "post_detail" post.pk %}">Image: {{ post.image.url }}</a></h3>#}
{#        <p>Description: {{ post.description }}</p>#}
{#        {% if request.user.is_authenticated %}#}
{#            <p><a href="{% url 'post_update' article.pk %}" class="btn btn-success">Update</a></p>#}
{#            <p><a href="{% url 'post_delete' article.pk %}" class="btn btn-danger">Delete</a></p>#}
{#        {% endif %}#}
{#    </div>#}

{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

posts/templates/partial/search.html
{% load django_bootstrap5 %}

<form action="" method="get" class="text-center">
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content='Найти' %}
</form>

posts/templates/partial/search_form.html
{% load django_bootstrap5 %}
{% csrf_token %}

<div class="container-fluid">
{% if query %}
<p class="find">Title containing "{{ query }}"
    {% with results.count as total_results %}
    found {{ total_results }} result {{ total_results|pluralize }}:</p>
{% endwith %}
<br><br>
<div class="search-results row row-cols-1 row-cols-md-2 g-4">
    {% for item in queryset %}
    <div class="fw-bold">Title: {{ item.email }}</div>
    </div>
    {% empty %}
    <p class="find">There are no results for your query.</p>
    {% endfor %}
    <span class="button_padding"><a href="{% url 'index' %}" class="btn btn-info">Search again</a></span>
    {% else %}
    <div class="input-group">
        <form action="." method="get">
            <label for="id_query"></label>
            <input type="text" name="query" required="" id="id_query" placeholder="Enter">
            <button type="submit" class="btn btn-outline-info">search</button>
        </form>
    </div>
    {% endif %}
</div>
</div>